### ISSUE TITLE
Started a new world, broke some leaves, and this crash happened (LeafDrops.onDrops)

### ISSUE THREAD

**Issue by Lothrazar** [Kashdeya/Tiny-Progressions#2]
My config file says

```
# Sets the drop rate of Sticks from leaves. [range: 0 ~ 100, default: 10]
I:"Stick Drop Chance"=0
```

So i think the problem is that, the minimum value should be 1, since if i set it to zero it crashes.

... actually... I just now noticed the line below which has a true false to disable, i was setting that to zero to disable.

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at com.kashdeya.tinyprogressions.events.LeafDrops.onDrops(LeafDrops.java:33)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_371_LeafDrops_onDrops_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:717)

My config file

**Comment by Kashdeya** [comment]
Should be fixed in the newest version.
