### ISSUE TITLE
1.11.2: invalid ore dictionary registry errors in latest.log file.

### ISSUE THREAD

**Issue by Lothrazar** [Kashdeya/Tiny-Progressions#42]
[22:05:32] [Client thread/INFO]: Config Legacy Handler Finished
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name blockCharcoal has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:11)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name blockGlassDirty has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:12)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name blockReinforcedGlass has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:13)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name blockReinforcedObsidian has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:14)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name stoneAndesiteBrick has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:15)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name stoneDioriteBrick has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:16)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name stoneGraniteBrick has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:17)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name blockFlint has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:18)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name blockBone has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:19)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name smoothEndstone has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:586)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:20)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: ****************************************
[22:05:32] [Client thread/WARN]: * Invalid registration attempt for an Ore Dictionary item with name ingotFlint has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:601)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:587)
[22:05:32] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:585)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.handlers.OreDictHandler.init(OreDictHandler.java:21)
[22:05:32] [Client thread/WARN]: *  at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:53)
[22:05:32] [Client thread/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...

**Comment by Kashdeya** [comment]
should be fixed in the newest versions.
